export const SHORT_SCROLL_TOP_THRESHOLD = 3;
export const PAGE_SIDE_PADDING_PX = 48;
export const PAGE_BOTTOM_PADDING_PX = 48;
export const BACKGROUND_COVER_CONTENT_PX = 36;
export const MINIMIZED_HEADER_WRAPPER_HEIGHT_PX = 66;
export const MINIMIZED_HEADER_WRAPPER_WITH_TAIL_HEIGHT_PX = 60;

// Deprecated
export const TAIL_TOP_PADDING_PX = 24;
export const SCROLL_TOP_THRESHOLD = 20;
